# Generated by Django 5.2.11 on 2026-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_admissao_user_data_demissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tempo_hora_extra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
