# Generated by Django 5.2.11 on 2026-02-18 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('horario_regular', 'Horário Regular'), ('hora_extra', 'Hora Extra'), ('horario_irregular', 'Horário Irregular'), ('falta', 'Falta')], default='horario_regular', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
